import { PrismaClient } from "../generated/prisma/client.ts";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dbPath = path.resolve(__dirname, "../dev.db");

const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

const events = [
  {
    name: "Roman Empire",
    from: "27 BC",
    to: "476 AD",
    yearFrom: -27,
    yearTo: 476,
    colour: "#e63946",
    locations: JSON.stringify([
      "ITA",
      "GRC",
      "TUR",
      "EGY",
      "LBY",
      "TUN",
      "DZA",
      "ESP",
      "PRT",
      "FRA",
      "GBR",
      "DEU",
      "AUT",
      "HRV",
      "SRB",
      "BGR",
      "ROU",
      "SYR",
      "LBN",
      "ISR",
      "JOR",
      "IRQ",
      "MAR",
    ]),
    influencedBy: JSON.stringify([]),
  },
  {
    name: "Mongol Empire",
    from: "1206",
    to: "1368",
    yearFrom: 1206,
    yearTo: 1368,
    colour: "#f59e0b",
    locations: JSON.stringify([
      "MNG",
      "CHN",
      "RUS",
      "KAZ",
      "UZB",
      "TKM",
      "AFG",
      "IRN",
      "IRQ",
      "PAK",
      "KGZ",
      "TJK",
      "KOR",
      "GEO",
      "ARM",
      "AZE",
      "HUN",
      "POL",
      "UKR",
    ]),
    influencedBy: JSON.stringify([]),
  },
  {
    name: "Black Plague",
    from: "1347",
    to: "1353",
    yearFrom: 1347,
    yearTo: 1353,
    colour: "#065f46",
    locations: JSON.stringify([
      "ITA",
      "FRA",
      "ESP",
      "PRT",
      "GBR",
      "DEU",
      "AUT",
      "POL",
      "CZE",
      "HUN",
      "ROU",
      "BGR",
      "GRC",
      "TUR",
      "EGY",
      "SYR",
      "NOR",
      "SWE",
      "DNK",
      "NLD",
      "BEL",
      "CHE",
      "RUS",
      "IRQ",
      "MAR",
      "DZA",
      "TUN",
    ]),
    influencedBy: JSON.stringify(["Mongol Empire"]),
  },
  {
    name: "Ottoman Empire",
    from: "1299",
    to: "1922",
    yearFrom: 1299,
    yearTo: 1922,
    colour: "#dc2626",
    locations: JSON.stringify([
      "TUR",
      "GRC",
      "BGR",
      "ROU",
      "SRB",
      "HUN",
      "EGY",
      "IRQ",
      "SYR",
      "LBN",
      "ISR",
      "JOR",
      "SAU",
      "YEM",
      "LBY",
      "TUN",
      "DZA",
      "ALB",
      "MKD",
      "BIH",
      "MNE",
      "HRV",
    ]),
    influencedBy: JSON.stringify(["Roman Empire", "Mongol Empire"]),
  },
  {
    name: "British Empire",
    from: "1583",
    to: "1997",
    yearFrom: 1583,
    yearTo: 1997,
    colour: "#1e3a5f",
    locations: JSON.stringify([
      "GBR",
      "IRL",
      "CAN",
      "USA",
      "AUS",
      "NZL",
      "IND",
      "PAK",
      "BGD",
      "ZAF",
      "KEN",
      "NGA",
      "GHA",
      "EGY",
      "SDN",
      "MYS",
      "SGP",
      "HKG",
      "MMR",
      "JMA",
      "TTO",
      "BRB",
      "GUY",
      "SLE",
      "ZWE",
      "ZMB",
      "MWI",
      "BWA",
    ]),
    influencedBy: JSON.stringify(["Roman Empire", "Spanish Empire"]),
  },
  {
    name: "Spanish Empire",
    from: "1492",
    to: "1976",
    yearFrom: 1492,
    yearTo: 1976,
    colour: "#ca8a04",
    locations: JSON.stringify([
      "ESP",
      "MEX",
      "PER",
      "COL",
      "ARG",
      "CHL",
      "VEN",
      "ECU",
      "BOL",
      "PRY",
      "URY",
      "CUB",
      "PHL",
      "GTM",
      "HND",
      "SLV",
      "NIC",
      "CRI",
      "PAN",
      "DOM",
    ]),
    influencedBy: JSON.stringify(["Roman Empire"]),
  },
  {
    name: "World War I",
    from: "1914",
    to: "1918",
    yearFrom: 1914,
    yearTo: 1918,
    colour: "#7f1d1d",
    locations: JSON.stringify([
      "FRA",
      "DEU",
      "GBR",
      "RUS",
      "AUT",
      "ITA",
      "TUR",
      "USA",
      "BEL",
      "SRB",
      "ROU",
      "BGR",
      "GRC",
      "JPN",
      "AUS",
      "CAN",
      "NZL",
      "ZAF",
      "IND",
      "EGY",
    ]),
    influencedBy: JSON.stringify(["Ottoman Empire", "British Empire"]),
  },
  {
    name: "World War II",
    from: "1939",
    to: "1945",
    yearFrom: 1939,
    yearTo: 1945,
    colour: "#450a0a",
    locations: JSON.stringify([
      "DEU",
      "FRA",
      "GBR",
      "RUS",
      "USA",
      "JPN",
      "CHN",
      "ITA",
      "POL",
      "AUT",
      "CZE",
      "NLD",
      "BEL",
      "NOR",
      "DNK",
      "GRC",
      "YUG",
      "EGY",
      "LBY",
      "TUN",
      "PHL",
      "MMR",
      "IND",
      "AUS",
      "CAN",
      "BRA",
      "MEX",
      "FIN",
      "HUN",
      "ROU",
      "BGR",
    ]),
    influencedBy: JSON.stringify(["World War I"]),
  },
  {
    name: "Cold War",
    from: "1947",
    to: "1991",
    yearFrom: 1947,
    yearTo: 1991,
    colour: "#6366f1",
    locations: JSON.stringify([
      "USA",
      "RUS",
      "DEU",
      "POL",
      "CZE",
      "HUN",
      "ROU",
      "BGR",
      "CUB",
      "VNM",
      "KOR",
      "PRK",
      "CHN",
      "AFG",
      "GBR",
      "FRA",
      "TUR",
      "JPN",
      "ITA",
      "NOR",
    ]),
    influencedBy: JSON.stringify(["World War II"]),
  },
  {
    name: "COVID-19 Pandemic",
    from: "2019",
    to: "2023",
    yearFrom: 2019,
    yearTo: 2023,
    colour: "#7c3aed",
    locations: JSON.stringify([
      "CHN",
      "ITA",
      "ESP",
      "FRA",
      "DEU",
      "GBR",
      "USA",
      "BRA",
      "IND",
      "RUS",
      "JPN",
      "KOR",
      "AUS",
      "CAN",
      "MEX",
      "ARG",
      "ZAF",
      "NGA",
      "EGY",
      "TUR",
      "IRN",
      "IDN",
      "PHL",
      "THA",
      "COL",
      "PER",
      "CHL",
      "SAU",
      "PAK",
      "BGD",
    ]),
    influencedBy: JSON.stringify([]),
  },
];

async function main() {
  console.log("Seeding database...");

  // Clear existing data
  await prisma.timelineEvent.deleteMany();
  await prisma.setting.deleteMany();

  // Insert events
  for (const event of events) {
    await prisma.timelineEvent.create({ data: event });
  }

  // Insert default settings
  await prisma.setting.createMany({
    data: [{ key: "playSpeed", value: "10" }],
  });

  console.log(`Seeded ${events.length} timeline events.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
