import { PrismaClient } from "../generated/prisma/client.ts";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dbPath = path.resolve(__dirname, "../dev.db");

const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

function wikipediaLinkForEvent(name: string): string {
  const slug = encodeURIComponent(name.replace(/\s+/g, "_"));
  return `https://en.wikipedia.org/wiki/${slug}`;
}

const events = [
  {
    name: "Sumerian Civilization",
    from: "4500 BC",
    to: "1900 BC",
    yearFrom: -4500,
    yearTo: -1900,
    colour: "#92400e",
    locations: JSON.stringify(["IRQ", "KWT"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "mesopotamia", "city-states"]),
    featured: true,
  },
  {
    name: "Akkadian Empire",
    from: "2334 BC",
    to: "2154 BC",
    yearFrom: -2334,
    yearTo: -2154,
    colour: "#7c3f00",
    locations: JSON.stringify(["IRQ", "SYR", "IRN", "TUR"]),
    influencedBy: JSON.stringify(["Sumerian Civilization"]),
    category: "Empire",
    tags: JSON.stringify(["ancient", "middle-east", "mesopotamia"]),
    featured: false,
  },
  {
    name: "Neo-Assyrian Empire",
    from: "911 BC",
    to: "609 BC",
    yearFrom: -911,
    yearTo: -609,
    colour: "#92400e",
    locations: JSON.stringify([
      "IRQ",
      "SYR",
      "TUR",
      "IRN",
      "EGY",
      "ISR",
      "JOR",
    ]),
    influencedBy: JSON.stringify(["Akkadian Empire"]),
    category: "Empire",
    tags: JSON.stringify(["ancient", "middle-east", "mesopotamia", "iron-age"]),
    featured: false,
  },
  {
    name: "Achaemenid Empire",
    from: "550 BC",
    to: "330 BC",
    yearFrom: -550,
    yearTo: -330,
    colour: "#9a3412",
    locations: JSON.stringify([
      "IRN",
      "IRQ",
      "TUR",
      "EGY",
      "SYR",
      "JOR",
      "ISR",
      "AFG",
      "PAK",
      "UZB",
      "TKM",
      "AZE",
      "ARM",
      "GEO",
    ]),
    influencedBy: JSON.stringify(["Neo-Assyrian Empire"]),
    category: "Empire",
    tags: JSON.stringify(["ancient", "middle-east", "persia", "imperial"]),
    featured: true,
  },
  {
    name: "Indus Valley Civilization",
    from: "3300 BC",
    to: "1300 BC",
    yearFrom: -3300,
    yearTo: -1300,
    colour: "#0f766e",
    locations: JSON.stringify(["PAK", "IND", "AFG"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "south-asia", "urbanization"]),
    featured: false,
  },
  {
    name: "Ancient Egypt",
    from: "3100 BC",
    to: "30 BC",
    yearFrom: -3100,
    yearTo: -30,
    colour: "#d97706",
    locations: JSON.stringify(["EGY", "SDN"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "africa", "nile"]),
    featured: true,
  },
  {
    name: "Kingdom of Kush",
    from: "1070 BC",
    to: "350",
    yearFrom: -1070,
    yearTo: 350,
    colour: "#a16207",
    locations: JSON.stringify(["SDN", "EGY"]),
    influencedBy: JSON.stringify(["Ancient Egypt"]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "africa", "nile", "nubia"]),
    featured: false,
  },
  {
    name: "Carthaginian Civilization",
    from: "814 BC",
    to: "146 BC",
    yearFrom: -814,
    yearTo: -146,
    colour: "#b45309",
    locations: JSON.stringify(["TUN", "LBY", "DZA", "MAR", "ESP"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "africa", "mediterranean", "trade"]),
    featured: true,
  },
  {
    name: "Ancient Greece",
    from: "800 BC",
    to: "146 BC",
    yearFrom: -800,
    yearTo: -146,
    colour: "#2563eb",
    locations: JSON.stringify(["GRC", "TUR", "CYP", "ITA"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "mediterranean", "philosophy"]),
    featured: true,
  },
  {
    name: "Minoan Civilization",
    from: "3000 BC",
    to: "1100 BC",
    yearFrom: -3000,
    yearTo: -1100,
    colour: "#0ea5e9",
    locations: JSON.stringify(["GRC"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "europe", "aegean", "bronze-age"]),
    featured: false,
  },
  {
    name: "Mycenaean Civilization",
    from: "1600 BC",
    to: "1100 BC",
    yearFrom: -1600,
    yearTo: -1100,
    colour: "#0284c7",
    locations: JSON.stringify(["GRC", "TUR"]),
    influencedBy: JSON.stringify(["Minoan Civilization"]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "europe", "aegean", "bronze-age"]),
    featured: false,
  },
  {
    name: "Olmec Civilization",
    from: "1500 BC",
    to: "400 BC",
    yearFrom: -1500,
    yearTo: -400,
    colour: "#0ea5a4",
    locations: JSON.stringify(["MEX"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "americas", "mesoamerica"]),
    featured: false,
  },
  {
    name: "Maya Civilization",
    from: "2000 BC",
    to: "1697",
    yearFrom: -2000,
    yearTo: 1697,
    colour: "#14b8a6",
    locations: JSON.stringify(["MEX", "GTM", "BLZ", "HND", "SLV"]),
    influencedBy: JSON.stringify(["Olmec Civilization"]),
    category: "Civilization",
    tags: JSON.stringify(["ancient", "americas", "mesoamerica", "astronomy"]),
    featured: true,
  },
  {
    name: "Mississippian Culture",
    from: "800",
    to: "1600",
    yearFrom: 800,
    yearTo: 1600,
    colour: "#22c55e",
    locations: JSON.stringify(["USA"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify(["americas", "north-america", "mound-builders"]),
    featured: false,
  },
  {
    name: "Aztec Empire",
    from: "1325",
    to: "1521",
    yearFrom: 1325,
    yearTo: 1521,
    colour: "#65a30d",
    locations: JSON.stringify(["MEX"]),
    influencedBy: JSON.stringify(["Maya Civilization"]),
    category: "Empire",
    tags: JSON.stringify(["americas", "mesoamerica", "pre-columbian"]),
    featured: true,
  },
  {
    name: "Inca Empire",
    from: "1438",
    to: "1533",
    yearFrom: 1438,
    yearTo: 1533,
    colour: "#16a34a",
    locations: JSON.stringify(["PER", "BOL", "ECU", "CHL", "ARG", "COL"]),
    influencedBy: JSON.stringify([]),
    category: "Empire",
    tags: JSON.stringify(["americas", "andes", "pre-columbian"]),
    featured: true,
  },
  {
    name: "Roman Empire",
    from: "27 BC",
    to: "476 AD",
    yearFrom: -27,
    yearTo: 476,
    colour: "#e63946",
    locations: JSON.stringify([
      "ITA",
      "GRC",
      "TUR",
      "EGY",
      "LBY",
      "TUN",
      "DZA",
      "ESP",
      "PRT",
      "FRA",
      "GBR",
      "DEU",
      "AUT",
      "HRV",
      "SRB",
      "BGR",
      "ROU",
      "SYR",
      "LBN",
      "ISR",
      "JOR",
      "IRQ",
      "MAR",
    ]),
    influencedBy: JSON.stringify([]),
    category: "Empire",
    tags: JSON.stringify(["ancient", "europe", "mediterranean"]),
    featured: true,
  },
  {
    name: "Byzantine Empire",
    from: "330",
    to: "1453",
    yearFrom: 330,
    yearTo: 1453,
    colour: "#2563eb",
    locations: JSON.stringify([
      "TUR",
      "GRC",
      "BGR",
      "ROU",
      "SRB",
      "ALB",
      "MKD",
      "HRV",
      "ITA",
      "EGY",
      "SYR",
    ]),
    influencedBy: JSON.stringify(["Roman Empire"]),
    category: "Empire",
    tags: JSON.stringify(["europe", "mediterranean", "orthodox", "medieval"]),
    featured: true,
  },
  {
    name: "Holy Roman Empire",
    from: "962",
    to: "1806",
    yearFrom: 962,
    yearTo: 1806,
    colour: "#475569",
    locations: JSON.stringify([
      "DEU",
      "AUT",
      "CZE",
      "ITA",
      "BEL",
      "NLD",
      "CHE",
      "FRA",
      "POL",
    ]),
    influencedBy: JSON.stringify(["Roman Empire"]),
    category: "Empire",
    tags: JSON.stringify(["europe", "medieval", "central-europe"]),
    featured: false,
  },
  {
    name: "Kievan Rus",
    from: "882",
    to: "1240",
    yearFrom: 882,
    yearTo: 1240,
    colour: "#334155",
    locations: JSON.stringify(["UKR", "RUS", "BLR"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify(["europe", "eastern-europe", "medieval"]),
    featured: false,
  },
  {
    name: "Mongol Empire",
    from: "1206",
    to: "1368",
    yearFrom: 1206,
    yearTo: 1368,
    colour: "#f59e0b",
    locations: JSON.stringify([
      "MNG",
      "CHN",
      "RUS",
      "KAZ",
      "UZB",
      "TKM",
      "AFG",
      "IRN",
      "IRQ",
      "PAK",
      "KGZ",
      "TJK",
      "KOR",
      "GEO",
      "ARM",
      "AZE",
      "HUN",
      "POL",
      "UKR",
    ]),
    influencedBy: JSON.stringify([]),
    category: "Empire",
    tags: JSON.stringify(["asia", "steppe", "expansion"]),
    featured: true,
  },
  {
    name: "Black Plague",
    from: "1347",
    to: "1353",
    yearFrom: 1347,
    yearTo: 1353,
    colour: "#065f46",
    locations: JSON.stringify([
      "ITA",
      "FRA",
      "ESP",
      "PRT",
      "GBR",
      "DEU",
      "AUT",
      "POL",
      "CZE",
      "HUN",
      "ROU",
      "BGR",
      "GRC",
      "TUR",
      "EGY",
      "SYR",
      "NOR",
      "SWE",
      "DNK",
      "NLD",
      "BEL",
      "CHE",
      "RUS",
      "IRQ",
      "MAR",
      "DZA",
      "TUN",
    ]),
    influencedBy: JSON.stringify(["Mongol Empire"]),
    category: "Pandemic",
    tags: JSON.stringify(["disease", "europe", "medieval"]),
    featured: false,
  },
  {
    name: "Ottoman Empire",
    from: "1299",
    to: "1922",
    yearFrom: 1299,
    yearTo: 1922,
    colour: "#dc2626",
    locations: JSON.stringify([
      "TUR",
      "GRC",
      "BGR",
      "ROU",
      "SRB",
      "HUN",
      "EGY",
      "IRQ",
      "SYR",
      "LBN",
      "ISR",
      "JOR",
      "SAU",
      "YEM",
      "LBY",
      "TUN",
      "DZA",
      "ALB",
      "MKD",
      "BIH",
      "MNE",
      "HRV",
    ]),
    influencedBy: JSON.stringify(["Roman Empire", "Mongol Empire"]),
    category: "Empire",
    tags: JSON.stringify(["middle-east", "europe", "long-duration"]),
    featured: true,
  },
  {
    name: "British Empire",
    from: "1583",
    to: "1997",
    yearFrom: 1583,
    yearTo: 1997,
    colour: "#1e3a5f",
    locations: JSON.stringify([
      "GBR",
      "IRL",
      "CAN",
      "USA",
      "AUS",
      "NZL",
      "IND",
      "PAK",
      "BGD",
      "ZAF",
      "KEN",
      "NGA",
      "GHA",
      "EGY",
      "SDN",
      "MYS",
      "SGP",
      "HKG",
      "MMR",
      "JMA",
      "TTO",
      "BRB",
      "GUY",
      "SLE",
      "ZWE",
      "ZMB",
      "MWI",
      "BWA",
    ]),
    influencedBy: JSON.stringify(["Roman Empire", "Spanish Empire"]),
    category: "Empire",
    tags: JSON.stringify(["colonial", "global", "naval"]),
    featured: true,
  },
  {
    name: "Spanish Empire",
    from: "1492",
    to: "1976",
    yearFrom: 1492,
    yearTo: 1976,
    colour: "#ca8a04",
    locations: JSON.stringify([
      "ESP",
      "MEX",
      "PER",
      "COL",
      "ARG",
      "CHL",
      "VEN",
      "ECU",
      "BOL",
      "PRY",
      "URY",
      "CUB",
      "PHL",
      "GTM",
      "HND",
      "SLV",
      "NIC",
      "CRI",
      "PAN",
      "DOM",
    ]),
    influencedBy: JSON.stringify(["Roman Empire"]),
    category: "Empire",
    tags: JSON.stringify(["colonial", "americas", "global"]),
    featured: false,
  },
  {
    name: "World War I",
    from: "1914",
    to: "1918",
    yearFrom: 1914,
    yearTo: 1918,
    colour: "#7f1d1d",
    locations: JSON.stringify([
      "FRA",
      "DEU",
      "GBR",
      "RUS",
      "AUT",
      "ITA",
      "TUR",
      "USA",
      "BEL",
      "SRB",
      "ROU",
      "BGR",
      "GRC",
      "JPN",
      "AUS",
      "CAN",
      "NZL",
      "ZAF",
      "IND",
      "EGY",
    ]),
    influencedBy: JSON.stringify(["Ottoman Empire", "British Empire"]),
    category: "War",
    tags: JSON.stringify(["20th-century", "global", "europe"]),
    featured: true,
  },
  {
    name: "World War II",
    from: "1939",
    to: "1945",
    yearFrom: 1939,
    yearTo: 1945,
    colour: "#450a0a",
    locations: JSON.stringify([
      "DEU",
      "FRA",
      "GBR",
      "RUS",
      "USA",
      "CHN",
      "ITA",
      "POL",
      "AUT",
      "CZE",
      "NLD",
      "BEL",
      "NOR",
      "DNK",
      "GRC",
      "YUG",
      "EGY",
      "LBY",
      "TUN",
      "PHL",
      "MMR",
      "IND",
      "AUS",
      "CAN",
      "BRA",
      "MEX",
      "FIN",
      "HUN",
      "ROU",
      "BGR",
    ]),
    influencedBy: JSON.stringify(["World War I"]),
    category: "War",
    tags: JSON.stringify(["20th-century", "global", "allies-axis"]),
    featured: true,
  },
  {
    name: "Cold War",
    from: "1947",
    to: "1991",
    yearFrom: 1947,
    yearTo: 1991,
    colour: "#6366f1",
    locations: JSON.stringify([
      "USA",
      "RUS",
      "DEU",
      "POL",
      "CZE",
      "HUN",
      "ROU",
      "BGR",
      "CUB",
      "VNM",
      "KOR",
      "PRK",
      "CHN",
      "AFG",
      "GBR",
      "FRA",
      "TUR",
      "JPN",
      "ITA",
      "NOR",
    ]),
    influencedBy: JSON.stringify(["World War II"]),
    category: "Geopolitics",
    tags: JSON.stringify(["usa", "ussr", "proxy-war"]),
    featured: true,
  },
  {
    name: "COVID-19 Pandemic",
    from: "2019",
    to: "2023",
    yearFrom: 2019,
    yearTo: 2023,
    colour: "#7c3aed",
    locations: JSON.stringify([
      "CHN",
      "ITA",
      "ESP",
      "FRA",
      "DEU",
      "GBR",
      "USA",
      "BRA",
      "IND",
      "RUS",
      "JPN",
      "KOR",
      "AUS",
      "CAN",
      "MEX",
      "ARG",
      "ZAF",
      "NGA",
      "EGY",
      "TUR",
      "IRN",
      "IDN",
      "PHL",
      "THA",
      "COL",
      "PER",
      "CHL",
      "SAU",
      "PAK",
      "BGD",
    ]),
    influencedBy: JSON.stringify([]),
    category: "Pandemic",
    tags: JSON.stringify(["21st-century", "global", "public-health"]),
    featured: true,
  },
  {
    name: "Han Dynasty",
    from: "206 BC",
    to: "220 AD",
    yearFrom: -206,
    yearTo: 220,
    colour: "#0f766e",
    locations: JSON.stringify([
      "CHN",
      "MNG",
      "PRK",
      "KOR",
      "VNM",
      "KAZ",
      "KGZ",
      "TJK",
    ]),
    influencedBy: JSON.stringify([]),
    category: "Empire",
    tags: JSON.stringify(["ancient", "asia", "silk-road"]),
    featured: false,
  },
  {
    name: "Maurya Empire",
    from: "322 BC",
    to: "185 BC",
    yearFrom: -322,
    yearTo: -185,
    colour: "#7c2d12",
    locations: JSON.stringify(["IND", "PAK", "AFG", "BGD", "NPL"]),
    influencedBy: JSON.stringify(["Indus Valley Civilization"]),
    category: "Empire",
    tags: JSON.stringify(["ancient", "asia", "south-asia", "india"]),
    featured: true,
  },
  {
    name: "Gupta Empire",
    from: "320",
    to: "550",
    yearFrom: 320,
    yearTo: 550,
    colour: "#a16207",
    locations: JSON.stringify(["IND", "NPL", "BGD", "PAK"]),
    influencedBy: JSON.stringify(["Maurya Empire"]),
    category: "Empire",
    tags: JSON.stringify(["asia", "south-asia", "science", "golden-age"]),
    featured: false,
  },
  {
    name: "Tang Dynasty",
    from: "618",
    to: "907",
    yearFrom: 618,
    yearTo: 907,
    colour: "#b45309",
    locations: JSON.stringify(["CHN", "MNG", "PRK", "KOR", "VNM"]),
    influencedBy: JSON.stringify(["Han Dynasty"]),
    category: "Empire",
    tags: JSON.stringify(["asia", "china", "silk-road", "golden-age"]),
    featured: true,
  },
  {
    name: "Khmer Empire",
    from: "802",
    to: "1431",
    yearFrom: 802,
    yearTo: 1431,
    colour: "#0f766e",
    locations: JSON.stringify(["KHM", "THA", "LAO", "VNM"]),
    influencedBy: JSON.stringify([]),
    category: "Empire",
    tags: JSON.stringify(["asia", "southeast-asia", "angkor", "hydraulics"]),
    featured: false,
  },
  {
    name: "Srivijaya Empire",
    from: "650",
    to: "1377",
    yearFrom: 650,
    yearTo: 1377,
    colour: "#0369a1",
    locations: JSON.stringify(["IDN", "MYS", "SGP", "THA"]),
    influencedBy: JSON.stringify([]),
    category: "Empire",
    tags: JSON.stringify(["asia", "southeast-asia", "maritime", "trade"]),
    featured: false,
  },
  {
    name: "Abbasid Caliphate",
    from: "750",
    to: "1258",
    yearFrom: 750,
    yearTo: 1258,
    colour: "#166534",
    locations: JSON.stringify([
      "IRQ",
      "IRN",
      "SYR",
      "JOR",
      "SAU",
      "EGY",
      "TUR",
      "AFG",
      "PAK",
      "UZB",
      "TKM",
    ]),
    influencedBy: JSON.stringify(["Roman Empire"]),
    category: "Empire",
    tags: JSON.stringify(["middle-east", "science", "golden-age"]),
    featured: false,
  },
  {
    name: "Umayyad Caliphate",
    from: "661",
    to: "750",
    yearFrom: 661,
    yearTo: 750,
    colour: "#166534",
    locations: JSON.stringify([
      "SAU",
      "IRQ",
      "SYR",
      "JOR",
      "ISR",
      "EGY",
      "IRN",
      "TUR",
      "MAR",
      "DZA",
      "TUN",
      "ESP",
      "PRT",
      "AFG",
      "PAK",
    ]),
    influencedBy: JSON.stringify([]),
    category: "Empire",
    tags: JSON.stringify(["middle-east", "caliphate", "expansion"]),
    featured: false,
  },
  {
    name: "Safavid Empire",
    from: "1501",
    to: "1736",
    yearFrom: 1501,
    yearTo: 1736,
    colour: "#0f766e",
    locations: JSON.stringify([
      "IRN",
      "IRQ",
      "AZE",
      "ARM",
      "GEO",
      "AFG",
      "PAK",
      "TUR",
    ]),
    influencedBy: JSON.stringify(["Achaemenid Empire"]),
    category: "Empire",
    tags: JSON.stringify(["middle-east", "persia", "early-modern"]),
    featured: false,
  },
  {
    name: "Aksumite Empire",
    from: "100",
    to: "940",
    yearFrom: 100,
    yearTo: 940,
    colour: "#059669",
    locations: JSON.stringify(["ETH", "ERI", "SDN", "DJI", "YEM"]),
    influencedBy: JSON.stringify([]),
    category: "Empire",
    tags: JSON.stringify(["africa", "horn-of-africa", "trade", "christianity"]),
    featured: false,
  },
  {
    name: "Mali Empire",
    from: "1235",
    to: "1670",
    yearFrom: 1235,
    yearTo: 1670,
    colour: "#65a30d",
    locations: JSON.stringify(["MLI", "MRT", "SEN", "GIN", "NER", "BFA"]),
    influencedBy: JSON.stringify([]),
    category: "Empire",
    tags: JSON.stringify(["africa", "west-africa", "gold", "trade"]),
    featured: true,
  },
  {
    name: "Great Zimbabwe",
    from: "1100",
    to: "1450",
    yearFrom: 1100,
    yearTo: 1450,
    colour: "#0d9488",
    locations: JSON.stringify(["ZWE", "MOZ", "ZAF", "BWA"]),
    influencedBy: JSON.stringify([]),
    category: "Civilization",
    tags: JSON.stringify([
      "africa",
      "southern-africa",
      "trade",
      "stone-architecture",
    ]),
    featured: false,
  },
  {
    name: "Renaissance",
    from: "1300",
    to: "1600",
    yearFrom: 1300,
    yearTo: 1600,
    colour: "#9333ea",
    locations: JSON.stringify([
      "ITA",
      "FRA",
      "ESP",
      "PRT",
      "DEU",
      "NLD",
      "BEL",
      "GBR",
      "CHE",
      "AUT",
    ]),
    influencedBy: JSON.stringify(["Roman Empire"]),
    category: "Culture",
    tags: JSON.stringify(["art", "science", "europe"]),
    featured: false,
  },
  {
    name: "Age of Discovery",
    from: "1415",
    to: "1700",
    yearFrom: 1415,
    yearTo: 1700,
    colour: "#0369a1",
    locations: JSON.stringify([
      "PRT",
      "ESP",
      "GBR",
      "FRA",
      "NLD",
      "BRA",
      "MEX",
      "PER",
      "ARG",
      "ZAF",
      "IND",
      "IDN",
      "PHL",
    ]),
    influencedBy: JSON.stringify(["Renaissance"]),
    category: "Exploration",
    tags: JSON.stringify(["navigation", "colonial", "trade"]),
    featured: false,
  },
  {
    name: "Industrial Revolution",
    from: "1760",
    to: "1840",
    yearFrom: 1760,
    yearTo: 1840,
    colour: "#b45309",
    locations: JSON.stringify([
      "GBR",
      "FRA",
      "DEU",
      "BEL",
      "NLD",
      "USA",
      "ITA",
      "RUS",
    ]),
    influencedBy: JSON.stringify(["British Empire"]),
    category: "Industry",
    tags: JSON.stringify(["steam", "manufacturing", "urbanization"]),
    featured: true,
  },
  {
    name: "French Revolution",
    from: "1789",
    to: "1799",
    yearFrom: 1789,
    yearTo: 1799,
    colour: "#be123c",
    locations: JSON.stringify([
      "FRA",
      "BEL",
      "DEU",
      "ITA",
      "ESP",
      "NLD",
      "CHE",
      "AUT",
      "POL",
    ]),
    influencedBy: JSON.stringify([]),
    category: "Revolution",
    tags: JSON.stringify(["politics", "europe", "republic"]),
    featured: false,
  },
  {
    name: "Decolonization Wave",
    from: "1945",
    to: "1980",
    yearFrom: 1945,
    yearTo: 1980,
    colour: "#0ea5e9",
    locations: JSON.stringify([
      "IND",
      "PAK",
      "BGD",
      "IDN",
      "VNM",
      "DZA",
      "MAR",
      "TUN",
      "GHA",
      "NGA",
      "KEN",
      "ZAF",
      "EGY",
      "MYS",
    ]),
    influencedBy: JSON.stringify(["World War II"]),
    category: "Geopolitics",
    tags: JSON.stringify(["independence", "post-war", "nation-state"]),
    featured: true,
  },
  {
    name: "Space Age",
    from: "1957",
    to: "2026",
    yearFrom: 1957,
    yearTo: 2026,
    colour: "#1d4ed8",
    locations: JSON.stringify([
      "USA",
      "RUS",
      "KAZ",
      "CHN",
      "JPN",
      "IND",
      "FRA",
      "DEU",
      "CAN",
      "AUS",
      "BRA",
      "ISR",
      "IRN",
      "KOR",
    ]),
    influencedBy: JSON.stringify(["Cold War"]),
    category: "Science",
    tags: JSON.stringify(["space", "satellites", "technology"]),
    featured: true,
  },
  {
    name: "Internet Era",
    from: "1983",
    to: "2026",
    yearFrom: 1983,
    yearTo: 2026,
    colour: "#4f46e5",
    locations: JSON.stringify([
      "USA",
      "GBR",
      "DEU",
      "FRA",
      "NLD",
      "SWE",
      "NOR",
      "JPN",
      "KOR",
      "CHN",
      "IND",
      "BRA",
      "CAN",
      "AUS",
      "SGP",
      "ISR",
    ]),
    influencedBy: JSON.stringify(["Cold War"]),
    category: "Technology",
    tags: JSON.stringify(["internet", "digital", "globalization"]),
    featured: true,
  },
];

async function main() {
  console.log("Seeding database...");

  // Clear existing data
  await prisma.timelineEvent.deleteMany();
  await prisma.setting.deleteMany();

  // Insert events
  for (const event of events) {
    await prisma.timelineEvent.create({
      data: {
        ...event,
        link: wikipediaLinkForEvent(event.name),
      },
    });
  }

  // Insert default settings
  await prisma.setting.createMany({
    data: [{ key: "playSpeed", value: "10" }],
  });

  console.log(`Seeded ${events.length} timeline events.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
